import os
import logging
from typing import Optional
from github import Github, GithubException
from dotenv import load_dotenv

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

load_dotenv()

class BlogPostCreator:
    """Automates branch creation, committing files, and opening PRs via PyGithub."""

    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        if not self.token:
            raise ValueError("GITHUB_TOKEN not found in environment.")
        
        self.gh = Github(self.token)
        self.repo_name = os.getenv("TARGET_REPO", "krkn-chaos/website")
        try:
            self.repo = self.gh.get_repo(self.repo_name)
        except GithubException as e:
            logger.error(f"Error accessing repository {self.repo_name}: {e}")
            raise

    def create_pr(self, file_path: str, content: str, branch_name: str, title: str):
        """
        Creates a new branch, commits the file, and opens a draft PR.
        
        Args:
            file_path: Path to the file in the repository.
            content: Content of the file.
            branch_name: Name of the new branch.
            title: Title of the PR.
        """
        try:
            # 1. Get main branch sha
            main_branch = self.repo.get_branch("main")
            
            # 2. Create new branch
            try:
                self.repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)
                logger.info(f"Created branch: {branch_name}")
            except GithubException as e:
                if e.status == 422: # Branch already exists
                    logger.warning(f"Branch {branch_name} already exists. Updating it.")
                else:
                    raise

            # 3. Create or update the file
            try:
                existing_file = self.repo.get_contents(file_path, ref=branch_name)
                self.repo.update_file(
                    path=file_path,
                    message=f"Update {title}",
                    content=content,
                    sha=existing_file.sha,
                    branch=branch_name
                )
                logger.info(f"Updated file: {file_path}")
            except GithubException:
                self.repo.create_file(
                    path=file_path,
                    message=f"Add {title}",
                    content=content,
                    branch=branch_name
                )
                logger.info(f"Created file: {file_path}")

            # 4. Open draft PR
            try:
                pr = self.repo.create_pull(
                    title=title,
                    body="This is an automated monthly digest generated by the krkn-bot.",
                    base="main",
                    head=branch_name,
                    draft=True
                )
                logger.info(f"Opened draft PR: {pr.html_url}")
            except GithubException as e:
                if e.status == 422: # PR already exists
                    logger.info("PR already exists for this branch.")
                else:
                    raise

        except GithubException as e:
            logger.error(f"GitHub operation failed: {e}")
            raise

def main():
    import glob
    from datetime import datetime

    creator = BlogPostCreator()
    
    # Find the latest generated markdown file
    files = glob.glob("content/en/blog/whats-new/whats-new-*.md")
    if not files:
        logger.error("No generated blog posts found in content/en/blog/whats-new/")
        return
        
    # Sort by date in filename
    latest_file = sorted(files)[-1]
    with open(latest_file, "r", encoding="utf-8") as f:
        content = f.read()
        
    date_str = datetime.now().strftime("%Y-%m")
    branch_name = f"whats-new-{date_str}"
    title = f"What's New in krkn-chaos — {datetime.now().strftime('%B %Y')}"
    
    # Target path in repo
    repo_path = latest_file.replace("\\", "/") # Ensure forward slashes for Git
    
    creator.create_pr(repo_path, content, branch_name, title)

if __name__ == "__main__":
    main()
